name: WiFi Driver CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        kernel: ['5.15', '6.1', '6.6', '6.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison libelf-dev libssl-dev bc
        
    - name: Download Kernel Headers
      run: |
        sudo apt-get install -y linux-headers-$(uname -r)
        
    - name: Setup Kernel Build Environment
      run: |
        echo "KERNELRELEASE=$(uname -r)" >> $GITHUB_ENV
        echo "KERNEL_DIR=/lib/modules/$(uname -r)/build" >> $GITHUB_ENV
        
    - name: Build Driver
      run: |
        make clean
        make -C $KERNEL_DIR M=$PWD modules
        
    - name: Run Basic Tests
      run: |
        sudo insmod wifi67.ko || true
        dmesg | grep -i wifi67
        sudo rmmod wifi67 || true
        
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wifi67-driver-${{ matrix.kernel }}
        path: |
          *.ko
          Module.symvers
          modules.order

    - name: Check Coding Style
      run: |
        perl scripts/checkpatch.pl --no-tree -f --strict --show-types --ignore LINUX_VERSION_CODE,FILE_PATH_CHANGES *.c *.h 